version: "3.7"

services:
    wiki:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        image: deepaksood619/wiki:latest
        container_name: wiki
        environment:
            - DEBUG=True
        ports:
            - 8000:8000
        entrypoint:
            - /bin/bash
            - -c
            - |
                sleep infinity
                # git clean -f
                # git reset --hard
                # git pull
                # cd .layouts
                # npm i
                # npm run build
                # cd ..
                # git checkout -b docs
                # git add .layouts/public -f
                # git commit -m "added docs"
                # git subtree push --prefix .layouts/public origin docs
        # volumes:
        #     - .:/app/
