version: "3.7"

services:
    wiki:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        image: deepaksood619/wiki:latest
        container_name: wiki
        environment:
            - DEBUG=True
        ports:
            - 8000:8000
        entrypoint:
            - /bin/bash
            - -c
            - |
                sleep infinity
                # git clone https://github.com/deepaksood619/wiki.git
                # cd wiki/.layouts
                # npm i
                # npm run deploy
                # npm run build
                # cd ..
                # git subtree split --prefix '.layouts/public' -b docs
                # git push -f https://deepaksood619:xxx@github.com/deepaksood619/wiki.git docs:docs

                # git checkout -b docs
                # git add .layouts/public -f
                # git commit -m "added docs"
                # git subtree push --prefix .layouts/public origin docs
                # git subtree push --prefix .layouts/public https://deepaksood619:xxx@github.com/deepaksood619/wiki.git docs
        # volumes:
        #     - .:/app/
