version: "3.7"

services:
    onenote:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        image: onenote:latest
        container_name: onenote
        environment:
            - DEBUG=True
        ports:
            - 8000:8000
            - 4000:4000
        entrypoint:
            - /bin/bash
            - -c
            - |
                sleep infinity
                # cd .layouts && npm run develop
                # npm i -f
                # npm run develop
                # npm run build
        # volumes:
        #     - .:/app/
